// FAST SNAKE
let dot = document.querySelector(".dot");
let block = document.querySelector(".block");
let block2 = document.querySelector(".block2");
let block3 = document.querySelector(".block3");
let block4 = document.querySelector(".block4");
let block5 = document.querySelector(".block5");
let block6 = document.querySelector(".block6");
let block7 = document.querySelector(".block7");
let block8 = document.querySelector(".block8");
let block9 = document.querySelector(".block9");
let block10 = document.querySelector(".block10");
let block11 = document.querySelector(".block11");
let block12 = document.querySelector(".block12");
let block13 = document.querySelector(".block13");
let block14 = document.querySelector(".block14");
let block15 = document.querySelector(".block15");
let block16 = document.querySelector(".block16");
let block17 = document.querySelector(".block17");
let block18 = document.querySelector(".block18");
let block19 = document.querySelector(".block19");
let block20 = document.querySelector(".block20");
let block21 = document.querySelector(".block21");
let block22 = document.querySelector(".block22");
let block23 = document.querySelector(".block23");
let block24 = document.querySelector(".block24");
let block25 = document.querySelector(".block25");
let block26 = document.querySelector(".block26");
let block27 = document.querySelector(".block27");
let block28 = document.querySelector(".block28");
let block29 = document.querySelector(".block29");
let block30 = document.querySelector(".block30");
let block31 = document.querySelector(".block31");
let block32 = document.querySelector(".block32");
let block33 = document.querySelector(".block33");
let block34 = document.querySelector(".block34");
let block35 = document.querySelector(".block35");
let block36 = document.querySelector(".block36");
let block37 = document.querySelector(".block37");
let block38 = document.querySelector(".block38");
let block39 = document.querySelector(".block39");
let block40 = document.querySelector(".block40");
let block41 = document.querySelector(".block41");
let block42 = document.querySelector(".block42");
let block43 = document.querySelector(".block43");
let block44 = document.querySelector(".block44");
let block45 = document.querySelector(".block45");
let block46 = document.querySelector(".block46");
let block47 = document.querySelector(".block47");
let block48 = document.querySelector(".block48");
let block49 = document.querySelector(".block49");
let block50 = document.querySelector(".block50");

window.addEventListener("mousemove", (e)=> {
    let posX = e.clientX;
    let posY = e.clientY;
    dot.style.left = `${posX}px`;
    dot.style.top = `${posY}px`;
    block.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1100, fill: "forwards"});
    block2.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1200, fill: "forwards"});
    block3.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1300, fill: "forwards"});
    block4.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1400, fill: "forwards"});
    block5.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1500, fill: "forwards"});
    block6.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1600, fill: "forwards"});
    block7.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1700, fill: "forwards"});
    block8.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1800, fill: "forwards"});
    block9.animate({left: `${posX}px`, top: `${posY}px`},{duration: 1900, fill: "forwards"});
    block10.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2000, fill: "forwards"});
    block11.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2100, fill: "forwards"});
    block12.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2200, fill: "forwards"});
    block13.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2300, fill: "forwards"});
    block14.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2400, fill: "forwards"});
    block15.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2500, fill: "forwards"});
    block16.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2600, fill: "forwards"});
    block17.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2700, fill: "forwards"});
    block18.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2800, fill: "forwards"});
    block19.animate({left: `${posX}px`, top: `${posY}px`},{duration: 2900, fill: "forwards"});
    block20.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3000, fill: "forwards"});
    block21.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3100, fill: "forwards"});
    block22.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3200, fill: "forwards"});
    block23.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3300, fill: "forwards"});
    block24.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3400, fill: "forwards"});
    block25.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3500, fill: "forwards"});
    block26.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3600, fill: "forwards"});
    block27.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3700, fill: "forwards"});
    block28.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3800, fill: "forwards"});
    block29.animate({left: `${posX}px`, top: `${posY}px`},{duration: 3900, fill: "forwards"});
    block30.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4000, fill: "forwards"});
    block31.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4100, fill: "forwards"});
    block32.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4200, fill: "forwards"});
    block33.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4300, fill: "forwards"});
    block34.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4400, fill: "forwards"});
    block35.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4500, fill: "forwards"});
    block36.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4600, fill: "forwards"});
    block37.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4700, fill: "forwards"});
    block38.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4800, fill: "forwards"});
    block39.animate({left: `${posX}px`, top: `${posY}px`},{duration: 4900, fill: "forwards"});
    block40.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5000, fill: "forwards"});
    block41.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5100, fill: "forwards"});
    block42.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5200, fill: "forwards"});
    block43.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5300, fill: "forwards"});
    block44.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5400, fill: "forwards"});
    block45.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5500, fill: "forwards"});
    block46.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5600, fill: "forwards"});
    block47.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5700, fill: "forwards"});
    block48.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5800, fill: "forwards"});
    block49.animate({left: `${posX}px`, top: `${posY}px`},{duration: 5900, fill: "forwards"});
    block50.animate({left: `${posX}px`, top: `${posY}px`},{duration: 6000, fill: "forwards"});
});

//SLOW SNAKE
// let dot = document.querySelector(".dot");
// let block = document.querySelector(".block");
// let block2 = document.querySelector(".block2");
// let block3 = document.querySelector(".block3");
// let block4 = document.querySelector(".block4");
// let block5 = document.querySelector(".block5");
// let block6 = document.querySelector(".block6");
// let block7 = document.querySelector(".block7");
// let block8 = document.querySelector(".block8");
// let block9 = document.querySelector(".block9");
// let block10 = document.querySelector(".block10");
// let block11 = document.querySelector(".block11");
// let block12 = document.querySelector(".block12");
// let block13 = document.querySelector(".block13");
// let block14 = document.querySelector(".block14");
// let block15 = document.querySelector(".block15");
// let block16 = document.querySelector(".block16");
// let block17 = document.querySelector(".block17");
// let block18 = document.querySelector(".block18");
// let block19 = document.querySelector(".block19");
// let block20 = document.querySelector(".block20");
// let block21 = document.querySelector(".block21");
// let block22 = document.querySelector(".block22");
// let block23 = document.querySelector(".block23");
// let block24 = document.querySelector(".block24");
// let block25 = document.querySelector(".block25");
// let block26 = document.querySelector(".block26");
// let block27 = document.querySelector(".block27");
// let block28 = document.querySelector(".block28");
// let block29 = document.querySelector(".block29");
// let block30 = document.querySelector(".block30");
// let block31 = document.querySelector(".block31");
// let block32 = document.querySelector(".block32");
// let block33 = document.querySelector(".block33");
// let block34 = document.querySelector(".block34");
// let block35 = document.querySelector(".block35");
// let block36 = document.querySelector(".block36");
// let block37 = document.querySelector(".block37");
// let block38 = document.querySelector(".block38");
// let block39 = document.querySelector(".block39");
// let block40 = document.querySelector(".block40");
// let block41 = document.querySelector(".block41");
// let block42 = document.querySelector(".block42");
// let block43 = document.querySelector(".block43");
// let block44 = document.querySelector(".block44");
// let block45 = document.querySelector(".block45");
// let block46 = document.querySelector(".block46");
// let block47 = document.querySelector(".block47");
// let block48 = document.querySelector(".block48");
// let block49 = document.querySelector(".block49");
// let block50 = document.querySelector(".block50");

// window.addEventListener("mousemove", (e)=> {
//     let posX = e.clientX;
//     let posY = e.clientY;
//     dot.style.left = `${posX}px`;
//     dot.style.top = `${posY}px`;
//     block.animate({left: `${posX}px`, top: `${posY}px`},{duration: 11000, fill: "forwards"});
//     block2.animate({left: `${posX}px`, top: `${posY}px`},{duration: 12000, fill: "forwards"});
//     block3.animate({left: `${posX}px`, top: `${posY}px`},{duration: 13000, fill: "forwards"});
//     block4.animate({left: `${posX}px`, top: `${posY}px`},{duration: 14000, fill: "forwards"});
//     block5.animate({left: `${posX}px`, top: `${posY}px`},{duration: 15000, fill: "forwards"});
//     block6.animate({left: `${posX}px`, top: `${posY}px`},{duration: 16000, fill: "forwards"});
//     block7.animate({left: `${posX}px`, top: `${posY}px`},{duration: 17000, fill: "forwards"});
//     block8.animate({left: `${posX}px`, top: `${posY}px`},{duration: 18000, fill: "forwards"});
//     block9.animate({left: `${posX}px`, top: `${posY}px`},{duration: 19000, fill: "forwards"});
//     block10.animate({left: `${posX}px`, top: `${posY}px`},{duration: 20000, fill: "forwards"});
//     block11.animate({left: `${posX}px`, top: `${posY}px`},{duration: 21000, fill: "forwards"});
//     block12.animate({left: `${posX}px`, top: `${posY}px`},{duration: 22000, fill: "forwards"});
//     block13.animate({left: `${posX}px`, top: `${posY}px`},{duration: 23000, fill: "forwards"});
//     block14.animate({left: `${posX}px`, top: `${posY}px`},{duration: 24000, fill: "forwards"});
//     block15.animate({left: `${posX}px`, top: `${posY}px`},{duration: 25000, fill: "forwards"});
//     block16.animate({left: `${posX}px`, top: `${posY}px`},{duration: 26000, fill: "forwards"});
//     block17.animate({left: `${posX}px`, top: `${posY}px`},{duration: 27000, fill: "forwards"});
//     block18.animate({left: `${posX}px`, top: `${posY}px`},{duration: 28000, fill: "forwards"});
//     block19.animate({left: `${posX}px`, top: `${posY}px`},{duration: 29000, fill: "forwards"});
//     block20.animate({left: `${posX}px`, top: `${posY}px`},{duration: 30000, fill: "forwards"});
//     block21.animate({left: `${posX}px`, top: `${posY}px`},{duration: 31000, fill: "forwards"});
//     block22.animate({left: `${posX}px`, top: `${posY}px`},{duration: 32000, fill: "forwards"});
//     block23.animate({left: `${posX}px`, top: `${posY}px`},{duration: 33000, fill: "forwards"});
//     block24.animate({left: `${posX}px`, top: `${posY}px`},{duration: 34000, fill: "forwards"});
//     block25.animate({left: `${posX}px`, top: `${posY}px`},{duration: 35000, fill: "forwards"});
//     block26.animate({left: `${posX}px`, top: `${posY}px`},{duration: 36000, fill: "forwards"});
//     block27.animate({left: `${posX}px`, top: `${posY}px`},{duration: 37000, fill: "forwards"});
//     block28.animate({left: `${posX}px`, top: `${posY}px`},{duration: 38000, fill: "forwards"});
//     block29.animate({left: `${posX}px`, top: `${posY}px`},{duration: 39000, fill: "forwards"});
//     block30.animate({left: `${posX}px`, top: `${posY}px`},{duration: 40000, fill: "forwards"});
//     block31.animate({left: `${posX}px`, top: `${posY}px`},{duration: 41000, fill: "forwards"});
//     block32.animate({left: `${posX}px`, top: `${posY}px`},{duration: 42000, fill: "forwards"});
//     block33.animate({left: `${posX}px`, top: `${posY}px`},{duration: 43000, fill: "forwards"});
//     block34.animate({left: `${posX}px`, top: `${posY}px`},{duration: 44000, fill: "forwards"});
//     block35.animate({left: `${posX}px`, top: `${posY}px`},{duration: 45000, fill: "forwards"});
//     block36.animate({left: `${posX}px`, top: `${posY}px`},{duration: 46000, fill: "forwards"});
//     block37.animate({left: `${posX}px`, top: `${posY}px`},{duration: 47000, fill: "forwards"});
//     block38.animate({left: `${posX}px`, top: `${posY}px`},{duration: 48000, fill: "forwards"});
//     block39.animate({left: `${posX}px`, top: `${posY}px`},{duration: 49000, fill: "forwards"});
//     block40.animate({left: `${posX}px`, top: `${posY}px`},{duration: 50000, fill: "forwards"});
//     block41.animate({left: `${posX}px`, top: `${posY}px`},{duration: 51000, fill: "forwards"});
//     block42.animate({left: `${posX}px`, top: `${posY}px`},{duration: 52000, fill: "forwards"});
//     block43.animate({left: `${posX}px`, top: `${posY}px`},{duration: 53000, fill: "forwards"});
//     block44.animate({left: `${posX}px`, top: `${posY}px`},{duration: 54000, fill: "forwards"});
//     block45.animate({left: `${posX}px`, top: `${posY}px`},{duration: 55000, fill: "forwards"});
//     block46.animate({left: `${posX}px`, top: `${posY}px`},{duration: 56000, fill: "forwards"});
//     block47.animate({left: `${posX}px`, top: `${posY}px`},{duration: 57000, fill: "forwards"});
//     block48.animate({left: `${posX}px`, top: `${posY}px`},{duration: 58000, fill: "forwards"});
//     block49.animate({left: `${posX}px`, top: `${posY}px`},{duration: 59000, fill: "forwards"});
//     block50.animate({left: `${posX}px`, top: `${posY}px`},{duration: 60000, fill: "forwards"});
// });